alias apt='sudo apt'
alias cat='bat --paging=never --tabs=8'
alias chmod='chmod --verbose'
alias chown='chown --verbose'
alias code='code -g'
alias cp='cp --interactive --verbose'
alias dd='dd status=progress'
alias df='df --human-readable --local --exclude-type="tmpfs"'
alias du='du --human-readable'
alias dmesg='sudo dmesg -T'
alias du='du --human-readable'
alias free='free --human --total'
alias fstrim='sudo fstrim --verbose'
alias grep='grep --color=auto --exclude-dir=.git --binary-files=without-match --line-number'
alias ll='exa --color=auto --all --sort=Name --across --classify --long'
alias ln='ln --interactive --verbose'
alias ls='exa --color=auto --all --sort=Name --across --classify'
alias lspci='sudo lspci'
alias mkdir='mkdir --verbose'
alias mount='sudo mount'
alias mv='mv --interactive --verbose'
alias open='xdg-open'
alias poweroff='sudo poweroff'
alias umount='sudo umount'
alias uname='uname --all'
alias updatedb='sudo updatedb'
alias reboot='sudo reboot'
alias reset='tput reset'
alias rm='rm --interactive --verbose'
alias su='su --shell=$SHELL'
alias tree='tree -C'

